server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountsDB
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  # provided for a demo of how to use SPRING PROFILES
  # profiles:
    # active: prod

# provided for a demo of how to use @ConfigurationProperties
accounts:
  message: "Welcome to bank API (Accounts/default)"
  contactDetails:
    name: "Rare Wind"
    email: "rarewind@rarewind.com"
  onCallSupport:
    - 21345654783
    - 23456785467