server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cardsDB
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# demonstration of config server
cards:
  message: "Welcome to bank API (Cards/default)"
  contactDetails:
    name: "Rare Wind"
    email: "rarewind@rarewind.com"
  onCallSupport:
    - 21345654783
    - 23456785467