server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# demonstration of config server
cards:
  message: "Welcome to bank API (Cards/default)"
  contactDetails:
    name: "Rare Wind"
    email: "rarewind@rarewind.com"
  onCallSupport:
    - 21345654783
    - 23456785467