server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loansDB
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


# demonstration of config server
loans:
  message: "Welcome to bank API (Loans/default)"
  contactDetails:
    name: "Rare Wind"
    email: "rarewind@rarewind.com"
  onCallSupport:
    - 21345654783
    - 23456785467